# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c38bf5f077066da40ccd7e3248847e07c5ae14556c40509b5c1f1c522e7048da2681599f8c8375a1cea7699ab562eea7aa17329b72d50c10773c140e1cff5908

test:
  secret_key_base: b889392a0d75c50d629a3cb361e834ed3a3dc3a3f4e6ed64021c425d59524e3aa9b73fbafad62d4b91a68fb45de8aad1ba45fe3dff9b190caa7b28508549f139

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
